# Generated by Django 5.1 on 2024-09-16 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoManager', '0002_videogenerationqueue_videogenerationqueueitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogenerationqueueitem',
            name='waitTime',
        ),
        migrations.AddField(
            model_name='videogenerationqueueitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videogenerationqueueitem',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
