# Generated by Django 5.1 on 2024-09-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoManager', '0003_remove_videogenerationqueueitem_waittime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogenerationqueue',
            name='replicId',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
