# Generated by Django 5.1 on 2024-09-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoManager', '0004_videogenerationqueue_replicid'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogenerationqueueitem',
            name='url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
