# Generated by Django 5.1 on 2024-09-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='replicaName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
