# Generated by Django 5.1 on 2024-09-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
